# fly.toml app configuration file generated for matseliukh-portfolio on 2023-08-23T14:55:19+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "matseliukh-portfolio"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "waw"
processes = []

[build]

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
