# fly.toml app configuration file generated for matseliukh-portfolio-back-end on 2023-08-24T20:37:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "matseliukh-portfolio-back-end"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "volodymyr92/portfolio-back-end:latest"

[env]
  PORT = "3000"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
